// // export default {
// //   index: {
// //     title: "Home",
// //     display: "hidden",
// //   },
// // };

// // export default {
// //   index: {
// //     title: "Getting Started",
// //     theme: {
// //       toc: true,
// //     },
// //   },
// // };

import type { MetaRecord } from "nextra";

const CHART: MetaRecord = {
  AreaChart: "",
  BarChart: "",
  CandlestickChart: "",
  DonutChart: "",
  GaugeChart: "",
  Heatmap: "",
  LineChart: "",
  PieChart: "",
  RadarChart: "",
  ScatterChart: "",
};

const DATA_DISPLAY: MetaRecord = {
  DataGrid: "",
  DataTable: "",
  DataList: "",
  DataCard: "",
};

const FORM: MetaRecord = {
  LoginForm: "",
  RegisterForm: "",
  ContactForm: "",
  PaymentForm: "",
  FeedbackForm: "",
  SearchForm: "",
  SubscriptionForm: "",
  ProfileForm: "",
  InvoiceForm: "",
  SupportForm: "",
};

const SECTION: MetaRecord = {
  HeroSection: "",
  AboutSection: "",
  ServicesSection: "",
  TestimonialSection: "",
  FaqSection: "",
  ContactSection: "",
  FeatureSection: "",
  PricingSection: "",
  TeamSection: "",
  StatsSection: "",
};

export default {
  index: {
    type: "page",
    display: "hidden",
  },
  docs: {
    type: "page",
    title: "Documentation",

    items: {
      __1: {
        type: "separator",
        title: "Get Started",
      },
      index: "",
      Installation: "",

      __2: {
        type: "separator",
        title: "Animations & Motion",
      },

      FloatingCode: "",
      ParticleBackground: "",
      DraggableCards: "",
      MorphButton: "",
      CardStack: "",
      AnimatedList: "",
      SocialCard: "",
      __3: {
        type: "separator",
        title: "Components",
      },
      Accordion: "",
      ActionSheet: "",
      Button: "",
      Badge: "",

      Checkbox: "",
      Card: "",
      Dialog: "",
      Input: "",
      Label: "",
      RadioGroup: "",
      RangeSlider: "",
      Select: "",
      MultiSelect: "",

      Switch: "",
      Slider: "",
      Separator: "",

      Tabs: "",
      TextArea: "",
      Tooltip: "",
      MultiTooltip: "",

      __4: {
        type: "separator",
        title: "Coming Soon",
      },

      Alert: "",
      Analytics: "",
      Avatar: "",
      AvatarGroup: "",
      Banner: "",
      Breadcrumb: "",

      ButtonGroup: "",
      Calendar: "",
      Carousel: "",
      Chatbot: "",
      Chart: {
        items: CHART,
      },

      CheckboxGroup: "",
      Chip: "",
      CodeEditor: "",
      ColorPicker: "",
      ComboBox: "",
      CommandPalette: "",
      ContextMenu: "",
      CookieBanner: "",
      CopyButton: "",
      CreditCardInput: "",
      Dashboard: "",
      DataDisplay: {
        items: DATA_DISPLAY,
      },
      DatePicker: "",
      DateRangePicker: "",
      Divider: "",
      Drawer: "",
      Dropdown: "",
      EmptyState: "",
      ErrorBoundary: "",
      ErrorPage: "",
      Fab: "",
      FeatureGrid: "",
      Feedback: "",
      FileUpload: "",
      Filter: "",
      Footer: "",
      Form: {
        items: FORM,
      },
      Gallery: "",
      Grid: "",
      Header: "",
      HeroSection: "",
      HoverCard: "",
      IconButton: "",
      Image: "",
      InfiniteScroll: "",
      Invoice: "",
      JsonViewer: "",
      KanbanBoard: "",
      KeyboardShortcut: "",
      LazyLoad: "",
      Link: "",
      List: "",
      Loader: "",
      LoadingSpinner: "",
      MasonryGrid: "",
      MediaPlayer: "",
      Menu: "",
      Modal: "",
      Navigation: "",
      NewsletterSignup: "",
      Notification: "",
      NotificationCenter: "",
      NumberInput: "",
      OffCanvas: "",
      OnboardingTour: "",
      OtpInput: "",
      Pagination: "",
      PasswordInput: "",
      PaymentMethod: "",
      Popconfirm: "",
      Popover: "",
      PricingTable: "",
      Progress: "",
      ProgressBar: "",
      QrCode: "",
      QuickActions: "",
      Rating: "",
      SearchBox: "",
      Section: {
        items: SECTION,
      },
      Sheet: "",
      Sidebar: "",
      Skeleton: "",
      Snackbar: "",
      Spinner: "",
      Stack: "",
      Statistic: "",
      StatusIndicator: "",
      Stepper: "",
      Table: "",
      Tag: "",
      TagInput: "",
      TeamCard: "",
      TestimonialCard: "",
      Timeline: "",
      TimePicker: "",
      Toast: "",
      Toggle: "",
      Toolbar: "",
      TreeView: "",
      UploadZone: "",
      UserProfile: "",
      VideoPlayer: "",
      VirtualList: "",
      Wizard: "",
      Wysiwyg: "",
    },
  },
} as MetaRecord;
